# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

def pods
	pod 'DateTools'
	pod 'HyFoundation', :path => '..'
end

target 'HyFoundationDemo' do
	pods
end

target 'HyFoundationDemoTests' do
	pods
end

